---
title: "Intro to R Workshop"
format: html
editor: visual
author: "Katie Bunge"
date: 2026-03-18
---

I am learning R. This is my markdown segment.

Setup Chunk with Package Installation is included below:

```{r}
#| label: setup
source("training_source.R")

```

Examples of Numeric Values

```{r}

#This is a comment within the code segment. 

42
194
typeof(239.2)

```

Examples of Character Values

```{r}
#These are examples of character values. 

"This is a character string"
"SLIPJIG"
typeof("2/4 is a polka")

```

Working with Vectors

```{r}

#The operator 'c' stands for 'concatenate'

numbervector <- c(1,2,3)
charactervector <- c("a", "b", "c")
binaryvector <- c(TRUE, FALSE)
mixedvector <- c(1, "two", 3)

numbervector
charactervector
binaryvector
mixedvector

```

Exploring Lists

```{r}
my_list <- list(numbers = c(1,2,3), words = c("a","b"), mixed = list(TRUE, 5))
str(my_list)



```

Data Frames

```{r}
sampledf <- data.frame(id = 1:3,
                       mode = c("walk","car","bus"),
                       distance = c(1.2, 5.0, 3.4))
sampledf 

```

Importing and Viewing Data

Import = load data from a file
Cleaning = prepare column names 
Viewing = inspect rows and column types 

Importing data with rio

```{r}
csv_path <- "../data/raw/presurvey_20260317.csv"
survey_raw <- rio::import(csv_path)
print(survey_raw)
```

```{r}


```

```{r}


```
